import { writeFile } from 'node:fs/promises';

export interface DockerfileOptions {
  /** Node version (default: '20') */
  nodeVersion?: string;
  /** Port to expose (default: 3000) */
  port?: number;
  /** Package manager (default: 'pnpm') */
  packageManager?: 'pnpm' | 'npm' | 'yarn';
  /** Build command (default: 'pledge build') */
  buildCommand?: string;
  /** Start command (default: 'pledge start') */
  startCommand?: string;
  /** Include healthcheck (default: true) */
  healthcheck?: boolean;
  /** Healthcheck path (default: '/health') */
  healthcheckPath?: string;
  /** Output path (default: 'Dockerfile') */
  output?: string;
}

export async function generateDockerfile(options: DockerfileOptions = {}): Promise<string> {
  const {
    nodeVersion = '20',
    port = 3000,
    packageManager = 'pnpm',
    buildCommand = 'pledge build',
    healthcheck = true,
    healthcheckPath = '/health',
    output = 'Dockerfile',
  } = options;

  const installCmd = packageManager === 'pnpm' ? 'pnpm install --frozen-lockfile'
    : packageManager === 'yarn' ? 'yarn install --frozen-lockfile'
    : 'npm ci';

  const dockerfile = `# Generated by PledgeStack CLI
FROM node:${nodeVersion}-alpine AS base

# Install dependencies only when needed
FROM base AS deps
WORKDIR /app
COPY package.json ${packageManager === 'pnpm' ? 'pnpm-lock.yaml' : packageManager === 'yarn' ? 'yarn.lock' : 'package-lock.json'} ./
RUN ${installCmd}

# Build the application
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN ${buildCommand}

# Production image
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 pledgestack
COPY --from=builder /app/public ./public
COPY --from=builder /app/.pledge ./.pledge
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
USER pledgestack
EXPOSE ${port}
${healthcheck ? `HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD wget -qO- http://localhost:${port}${healthcheckPath} || exit 1` : ''}
CMD ["node", ".pledge/server.js"]
`;

  await writeFile(output, dockerfile);
  return dockerfile;
}

export async function generateDockerIgnore(): Promise<void> {
  const content = `node_modules
.git
.pledge
*.md
.env*
.pledge
coverage
.vscode
`;

  await writeFile('.dockerignore', content);
}

export async function generateDockerCompose(options: { port?: number; imageName?: string } = {}): Promise<string> {
  const { port = 3000, imageName = 'pledgestack-app' } = options;

  const compose = `version: '3.8'
services:
  app:
    image: ${imageName}
    build: .
    ports:
      - "${port}:${port}"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${port}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
`;

  await writeFile('docker-compose.yml', compose);
  return compose;
}
