import { validateEnv, type EnvSchema } from '@pledgestack/auth';

export interface EnvCheckOptions {
  /** Path to env file (default: '.env') */
  envFile?: string;
  /** Schema file path (default: 'pledge.config.ts') */
  schemaFile?: string;
  /** Custom schema */
  schema?: EnvSchema;
}

export async function checkEnv(options: EnvCheckOptions = {}): Promise<void> {
  const { schema } = options;

  if (!schema) {
    console.log('No env schema provided. Define env validation in pledge.config.ts or pass --schema');
    return;
  }

  console.log('Validating environment variables...\n');

  const result = validateEnv(schema);

  if (result.valid) {
    console.log('All environment variables are valid.');
    console.log(`\nPublic variables (${Object.keys(result.publicValues).length}):`);
    for (const [key, value] of Object.entries(result.publicValues)) {
      console.log(`  ${key}=${value}`);
    }
  } else {
    console.error('Environment validation failed:\n');
    for (const error of result.errors) {
      console.error(`  ${error.key}: ${error.message}`);
    }
    process.exit(1);
  }
}

export function generateEnvExample(schema: EnvSchema): string {
  const lines: string[] = ['# Environment variables for PledgeStack', '# Generated by pledge env:check', ''];

  for (const [key, rules] of Object.entries(schema)) {
    const comment = rules.required ? 'Required' : 'Optional';
    const typeInfo = rules.type;
    const defaultInfo = rules.default !== undefined ? ` (default: ${rules.default})` : '';
    const publicInfo = rules.public ? ' [PUBLIC]' : '';

    lines.push(`# ${key} - ${comment}, ${typeInfo}${defaultInfo}${publicInfo}`);
    if (rules.default !== undefined) {
      lines.push(`${key}=${rules.default}`);
    } else {
      lines.push(`${key}=`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
