/**
 * pledge storybook — Zero-config Storybook integration for PledgeStack.
 *
 * Goal #223: Auto-configures Storybook for PledgeStack projects:
 * - Generates .storybook/ directory with PledgeStack-aware config
 * - Detects app/ components and generates .stories.tsx files
 * - Configures Storybook to use PledgeStack's React 19 + Tailwind setup
 * - Supports both server and client components in stories
 */

import { readFile, writeFile, mkdir, readdir, access } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, relative } from 'node:path';
import type { PledgeConfig } from 'pledgestack-shared';

interface StorybookOptions {
  /** Force overwrite existing .storybook/ config */
  force?: boolean;
  /** Generate stories for all components (default: only components without stories) */
  all?: boolean;
}

/**
 * Generates the .storybook/main.ts config.
 */
function generateMainConfig(config: PledgeConfig): string {
  return `import type { StorybookConfig } from './types';

const config: StorybookConfig = {
  stories: [
    '../${config.appDir}/**/*.stories.@(ts|tsx|mdx)',
    '../${config.appDir}/**/*.@(ts|tsx)',
  ],
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
  typescript: {
    check: false,
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop: { parent?: { fileName?: string } }) =>
        prop.parent ? !/node_modules/.test(prop.parent.fileName ?? '') : true,
    },
  },
  staticDirs: ['../${config.publicDir}'],
};

export default config;
`;
}

/**
 * Generates the .storybook/preview.ts config.
 */
function generatePreviewConfig(): string {
  return `import type { Preview } from './types';
import '../${'app'}/globals.css';

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: '^on[A-Z].*' },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    layout: 'centered',
    backgrounds: {
      default: 'light',
      values: [
        { name: 'light', value: '#ffffff' },
        { name: 'dark', value: '#1a1a2e' },
        { name: 'pledge', value: '#6c5ce7' },
      ],
    },
  },
  globalTypes: {
    theme: {
      name: 'Theme',
      description: 'Theme mode',
      defaultValue: 'light',
      toolbar: {
        icon: 'circlehollow',
        items: [
          { value: 'light', icon: 'sun', title: 'Light' },
          { value: 'dark', icon: 'moon', title: 'Dark' },
        ],
      },
    },
  },
};

export default preview;
`;
}

/**
 * Generates a .storybook/types.ts file for type safety.
 */
function generateTypes(): string {
  return `// Auto-generated by pledge storybook
// Do not edit manually — run 'pledge storybook' to regenerate

export type StorybookConfig = {
  stories: string[];
  addons: string[];
  framework: {
    name: string;
    options: Record<string, unknown>;
  };
  docs?: {
    autodocs: string | boolean;
  };
  typescript?: {
    check?: boolean;
    reactDocgen?: string;
    reactDocgenTypescriptOptions?: Record<string, unknown>;
  };
  staticDirs?: string[];
};

export type Preview = {
  parameters: Record<string, unknown>;
  globalTypes?: Record<string, unknown>;
};

export type Story = {
  (args: Record<string, unknown>): unknown;
  args?: Record<string, unknown>;
  argTypes?: Record<string, unknown>;
  parameters?: Record<string, unknown>;
  decorators?: unknown[];
  loaders?: unknown[];
  play?: unknown;
};
`;
}

/**
 * Generates a default story for a component file.
 */
function generateDefaultStory(_componentPath: string, componentName: string, isClient: boolean): string {
  const storyName = `${componentName}Story`;

  return `import type { Story } from '../../.storybook/types';
${isClient ? '"use pledge:client";\n' : ''}
// Auto-generated story for ${componentName}
// Edit this file to customize the story

export const ${storyName}: Story = {
  render: () => null,
  parameters: {
    docs: {
      description: {
        story: 'Auto-generated story for ${componentName}. Edit to add real content.',
      },
    },
  },
};

export default {
  title: 'Components/${componentName}',
  component: ${storyName},
  tags: ['autodocs'],
};
`;
}

/**
 * Detects if a file is a client component.
 */
async function isClientComponent(filePath: string): Promise<boolean> {
  try {
    const content = await readFile(filePath, 'utf-8');
    return content.includes('"use pledge:client"') ||
           content.includes("'use pledge:client'") ||
           content.includes('"use client"') ||
           content.includes("'use client'");
  } catch {
    return false;
  }
}

/**
 * Extracts the component name from a file path.
 */
function getComponentName(filePath: string): string {
  const baseName = filePath.split(/[/\\]/).pop() ?? filePath;
  return baseName.replace(/\.(tsx|ts|jsx|js)$/, '');
}

/**
 * Checks if a file already has a corresponding .stories.tsx file.
 */
async function hasExistingStory(filePath: string): Promise<boolean> {
  const storyPath = filePath.replace(/\.(tsx|ts)$/, '.stories.tsx');
  try {
    await access(storyPath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Walks the app/ directory and finds component files.
 */
async function findComponents(appDir: string): Promise<string[]> {
  const components: string[] = [];

  async function walk(dir: string) {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        // Skip special directories
        if (entry.name.startsWith('_') || entry.name === 'api') continue;
        await walk(fullPath);
      } else if (/\.(tsx|ts)$/.test(entry.name)) {
        // Skip page.tsx, layout.tsx, loading.tsx, error.tsx, not-found.tsx, etc.
        const skip = ['page', 'layout', 'loading', 'error', 'not-found', 'template', 'default', 'head', 'route', 'middleware'];
        const baseName = entry.name.replace(/\.(tsx|ts)$/, '');
        if (!skip.includes(baseName)) {
          components.push(fullPath);
        }
      }
    }
  }

  if (existsSync(appDir)) {
    await walk(appDir);
  }

  return components;
}

/**
 * Runs the storybook command.
 */
export async function storybookCommand(opts: StorybookOptions = {}): Promise<void> {
  const { loadConfig } = await import('../config-loader');
  const config = await loadConfig();
  const rootDir = config.rootDir;

  const storybookDir = join(rootDir, '.storybook');

  console.log('\n  PledgeStack — Setting up Storybook...\n');

  // Check if .storybook already exists
  if (existsSync(storybookDir) && !opts.force) {
    console.error('  Error: .storybook/ already exists. Use --force to overwrite.\n');
    process.exit(1);
  }

  // 1. Create .storybook/ directory and config files
  console.log('  → Creating .storybook/ configuration...');
  await mkdir(storybookDir, { recursive: true });

  await writeFile(join(storybookDir, 'main.ts'), generateMainConfig(config), 'utf-8');
  console.log('    ✓ main.ts');

  await writeFile(join(storybookDir, 'preview.ts'), generatePreviewConfig(), 'utf-8');
  console.log('    ✓ preview.ts');

  await writeFile(join(storybookDir, 'types.ts'), generateTypes(), 'utf-8');
  console.log('    ✓ types.ts');

  // 2. Generate stories for components
  console.log('\n  → Scanning for components...');
  const appDir = join(rootDir, config.appDir);
  const components = await findComponents(appDir);
  console.log(`  ✓ Found ${components.length} component(s)\n`);

  let storiesGenerated = 0;
  let storiesSkipped = 0;

  for (const component of components) {
    const hasStory = await hasExistingStory(component);
    if (hasStory && !opts.all) {
      storiesSkipped++;
      continue;
    }

    const componentName = getComponentName(component);
    const isClient = await isClientComponent(component);
    const storyContent = generateDefaultStory(component, componentName, isClient);
    const storyPath = component.replace(/\.(tsx|ts)$/, '.stories.tsx');

    await writeFile(storyPath, storyContent, 'utf-8');
    console.log(`    ✓ ${relative(rootDir, storyPath)}`);
    storiesGenerated++;
  }

  if (storiesSkipped > 0) {
    console.log(`\n  Skipped ${storiesSkipped} component(s) with existing stories.`);
    console.log('  Use --all to regenerate all stories.\n');
  }

  // 3. Update package.json with Storybook scripts
  console.log('  → Updating package.json...');
  const pkgPath = join(rootDir, 'package.json');
  if (existsSync(pkgPath)) {
    const pkg = JSON.parse(await readFile(pkgPath, 'utf-8'));

    pkg.scripts = pkg.scripts ?? {};
    pkg.scripts.storybook = 'storybook dev -p 6006';
    pkg.scripts['build-storybook'] = 'storybook build';

    pkg.devDependencies = pkg.devDependencies ?? {};
    pkg.devDependencies['storybook'] = '^8.0.0';
    pkg.devDependencies['@storybook/react-vite'] = '^8.0.0';
    pkg.devDependencies['@storybook/addon-essentials'] = '^8.0.0';
    pkg.devDependencies['@storybook/addon-interactions'] = '^8.0.0';

    await writeFile(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf-8');
    console.log('    ✓ scripts and devDependencies added');
  }

  console.log(`\n  ✓ Storybook configured! ${storiesGenerated} stor${storiesGenerated === 1 ? 'y' : 'ies'} generated.\n`);
  console.log('  Next steps:');
  console.log('    1. Install dependencies: pnpm install');
  console.log('    2. Run Storybook: pnpm storybook\n');
  console.log('  Stories are auto-detected from app/ directory components.');
  console.log('  Add .stories.tsx files next to your components to customize.\n');
}
