/**
 * Route type generation — auto-generates `__pledge_route_types.d.ts` from the
 * file-based router at build time.
 *
 * Goal #221: Typed `params`, `searchParams`, layout chain types, route metadata.
 * Goal #224: Type-safe navigation with compile-time route param validation.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { scanAppDir } from '../fs/scanner';
import { resolveRoutes } from '../fs/resolver';
import type { PledgeConfig, ResolvedRoute } from 'pledgestack-shared';
import { ROUTE_GROUP_PATTERN } from 'pledgestack-shared';

/**
 * Extracts param names from a route pattern.
 * e.g. "/blog/:slug" → ["slug"]
 *      "/docs/*path" → ["path"]
 *      "/shop/:category/:id" → ["category", "id"]
 */
function extractParamNames(pattern: string): string[] {
  const names: string[] = [];
  for (const segment of pattern.split('/').filter(Boolean)) {
    if (segment.startsWith(':')) {
      names.push(segment.slice(1));
    } else if (segment.startsWith('*')) {
      names.push(segment.slice(1));
    }
  }
  return names;
}

/**
 * Determines if a param is a catch-all (string[] vs string).
 */
function isCatchAllParam(pattern: string, paramName: string): boolean {
  for (const segment of pattern.split('/').filter(Boolean)) {
    if (segment.startsWith('*') && segment.slice(1) === paramName) {
      return true;
    }
  }
  return false;
}

/**
 * Converts a route pattern to a TypeScript template literal type.
 * e.g. "/blog/:slug" → `/blog/${string}`
 *      "/docs/*path" → `/docs/${string}`
 *      "/shop" → "/shop"
 */
function patternToTypeLiteral(pattern: string): string {
  const segments = pattern.split('/').filter(Boolean);
  if (segments.length === 0) return '`/`';

  const typeSegments = segments.map((segment) => {
    if (segment.startsWith(':') || segment.startsWith('*')) {
      return '${string}';
    }
    return segment;
  });

  return '`/' + typeSegments.join('/') + '`';
}

/**
 * Generates the params type for a route.
 * e.g. { slug: string } or { path: string[] }
 */
function generateParamsType(pattern: string): string {
  const paramNames = extractParamNames(pattern);
  if (paramNames.length === 0) return 'Record<string, never>';

  const fields = paramNames.map((name) => {
    const isCatchAll = isCatchAllParam(pattern, name);
    return `  ${name}: ${isCatchAll ? 'string[]' : 'string'};`;
  });

  return `{ ${fields.join(' ')} }`;
}

/**
 * Sorts routes by specificity for the type declaration.
 * Static routes first, then dynamic, then catch-all.
 */
function sortRoutesBySpecificity(routes: ResolvedRoute[]): ResolvedRoute[] {
  return [...routes].sort((a, b) => {
    const aDynamic = a.pattern.includes(':') || a.pattern.includes('*');
    const bDynamic = b.pattern.includes(':') || b.pattern.includes('*');
    if (aDynamic && !bDynamic) return 1;
    if (!aDynamic && bDynamic) return -1;
    return a.pattern.localeCompare(b.pattern);
  });
}

/**
 * Generates the full TypeScript declaration file content.
 */
export function generateRouteTypes(
  routes: ResolvedRoute[],
  _config: PledgeConfig,
): string {
  const pageRoutes = sortRoutesBySpecificity(
    routes.filter((r) => !r.isLayout && !r.isNotFound && !r.isLoading && !r.isErrorBoundary),
  );

  const lines: string[] = [
    '/**',
    ' * AUTO-GENERATED by PledgeStack — DO NOT EDIT',
    ' * Generated from file-based router at build time.',
    ' * Goal #221: Type-safe route params, searchParams, and navigation.',
    ' */',
    '',
    '// ─── Route Patterns ──────────────────────────────────────────────────',
    '',
    '/** All known route patterns as a union of string literal types */',
    'export type RoutePattern =',
  ];

  if (pageRoutes.length === 0) {
    lines.push('  | `/`;');
  } else {
    for (const route of pageRoutes) {
      lines.push(`  | ${patternToTypeLiteral(route.pattern)}`);
    }
    lines.push('  | `/`;');
  }

  lines.push('');
  lines.push('// ─── Route Params ───────────────────────────────────────────────────');
  lines.push('');

  // Generate ParamsFor<P> conditional type
  lines.push('/**');
  lines.push(' * Extracts the params type for a given route pattern.');
  lines.push(' * Usage: type MyParams = ParamsFor<typeof pattern>;');
  lines.push(' */');
  lines.push('export type ParamsFor<P extends RoutePattern> =');
  for (const route of pageRoutes) {
    const literal = patternToTypeLiteral(route.pattern);
    const paramsType = generateParamsType(route.pattern);
    lines.push(`  P extends ${literal} ? ${paramsType} :`);
  }
  lines.push('  Record<string, string>;');

  lines.push('');
  lines.push('// ─── Route Metadata ─────────────────────────────────────────────────');
  lines.push('');

  lines.push('/** Metadata for a specific route */');
  lines.push('export interface RouteMeta {');
  lines.push('  pattern: RoutePattern;');
  lines.push('  mode: "ssr" | "ssg" | "rsc" | "api";');
  lines.push('  runtime: "node" | "edge";');
  lines.push('  isLayout: boolean;');
  lines.push('  isLoading: boolean;');
  lines.push('  isErrorBoundary: boolean;');
  lines.push('  isNotFound: boolean;');
  lines.push('}');

  lines.push('');
  lines.push('/** Map of route pattern → route metadata */');
  lines.push('export interface RouteMap {');
  for (const route of pageRoutes) {
    const literal = patternToTypeLiteral(route.pattern);
    lines.push(`  ${literal}: RouteMeta & { params: ${generateParamsType(route.pattern)} };`);
  }
  lines.push('}');

  lines.push('');
  lines.push('// ─── Type-Safe Navigation (#224) ────────────────────────────────────');
  lines.push('');

  lines.push('/**');
  lines.push(' * Type-safe route navigation.');
  lines.push(' * Provides compile-time validation of route params.');
  lines.push(' */');
  lines.push('export interface TypedRouter {');
  lines.push('  /**');
  lines.push('   * Navigate to a route with type-safe params.');
  lines.push('   * @example router.navigate("/blog/:slug", { params: { slug: "hello" } });');
  lines.push('   */');
  for (const route of pageRoutes) {
    const literal = patternToTypeLiteral(route.pattern);
    const paramsType = generateParamsType(route.pattern);
    const hasParams = extractParamNames(route.pattern).length > 0;
    if (hasParams) {
      lines.push(`  navigate(pattern: ${literal}, opts: { params: ${paramsType} }): void;`);
    } else {
      lines.push(`  navigate(pattern: ${literal}, opts?: { params?: Record<string, never> }): void;`);
    }
  }
  lines.push('  navigate(pattern: RoutePattern, opts?: { params?: Record<string, string> }): void;');
  lines.push('');

  lines.push('  /**');
  lines.push('   * Build a URL string from a route pattern and params.');
  lines.push('   * @example router.build("/blog/:slug", { params: { slug: "hello" } }) → "/blog/hello"');
  lines.push('   */');
  for (const route of pageRoutes) {
    const literal = patternToTypeLiteral(route.pattern);
    const paramsType = generateParamsType(route.pattern);
    const hasParams = extractParamNames(route.pattern).length > 0;
    if (hasParams) {
      lines.push(`  build(pattern: ${literal}, opts: { params: ${paramsType} }): string;`);
    } else {
      lines.push(`  build(pattern: ${literal}, opts?: { params?: Record<string, never> }): string;`);
    }
  }
  lines.push('  build(pattern: RoutePattern, opts?: { params?: Record<string, string> }): string;');
  lines.push('');

  lines.push('  /**');
  lines.push('   * Check if a pathname matches a known route.');
  lines.push('   */');
  lines.push('  match(pathname: string): { route: RouteMeta; params: Record<string, string> } | null;');
  lines.push('}');

  lines.push('');
  lines.push('// ─── Layout Chain Types ─────────────────────────────────────────────');
  lines.push('');

  const layoutRoutes = routes.filter((r) => r.isLayout);
  lines.push('/** Layout chain for a given route pattern */');
  lines.push('export type LayoutChain<P extends RoutePattern> =');
  if (layoutRoutes.length === 0) {
    lines.push('  [];');
  } else {
    for (const route of pageRoutes) {
      const literal = patternToTypeLiteral(route.pattern);
      // Find layouts that are prefixes of this route
      const matchingLayouts = layoutRoutes.filter((l) => {
        if (l.pattern === '/') return true;
        return route.pattern.startsWith(l.pattern + '/') || route.pattern === l.pattern;
      });
      const layoutPatterns = matchingLayouts.map((l) => `"${l.pattern}"`).join(' | ') || 'never';
      lines.push(`  P extends ${literal} ? (${layoutPatterns})[] :`);
    }
    lines.push('  string[];');
  }

  lines.push('');
  lines.push('// ─── Page Route Info ────────────────────────────────────────────────');
  lines.push('');

  lines.push('/** Full info for a page route including params and layout chain */');
  lines.push('export type RouteInfo<P extends RoutePattern> = {');
  lines.push('  pattern: P;');
  lines.push('  params: ParamsFor<P>;');
  lines.push('  searchParams: Record<string, string | string[] | undefined>;');
  lines.push('  layouts: LayoutChain<P>;');
  lines.push('};');

  lines.push('');
  lines.push('// ─── Route Group Helpers ────────────────────────────────────────────');
  lines.push('');

  // Collect route groups
  const groups = new Set<string>();
  for (const route of routes) {
    const segments = route.pattern.split('/').filter(Boolean);
    for (const seg of segments) {
      if (ROUTE_GROUP_PATTERN.test(seg)) {
        groups.add(seg.match(ROUTE_GROUP_PATTERN)![1]);
      }
    }
  }

  if (groups.size > 0) {
    lines.push('/** Known route groups */');
    lines.push('export type RouteGroup =');
    for (const group of groups) {
      lines.push(`  | "${group}"`);
    }
    lines.push('  | string;');
  }

  lines.push('');
  lines.push('// ─── Search Params ──────────────────────────────────────────────────');
  lines.push('');

  lines.push('/** Search params type — query string parameters */');
  lines.push('export type SearchParams = Record<string, string | string[] | undefined>;');

  lines.push('');
  lines.push('// ─── Link Component Props ───────────────────────────────────────────');
  lines.push('');

  lines.push('/** Props for the Link component with type-safe href */');
  lines.push('export interface TypedLinkProps<P extends RoutePattern> {');
  lines.push('  href: P;');
  lines.push('  params?: ParamsFor<P>;');
  lines.push('  children: React.ReactNode;');
  lines.push('}');

  lines.push('');
  return lines.join('\n');
}

/**
 * Scans the app directory, resolves routes, and writes the generated
 * type declaration file to the output directory.
 *
 * @param config - Resolved PledgeConfig
 * @param outputPath - Where to write the .d.ts file (default: <outDir>/__pledge_route_types.d.ts)
 */
export async function writeRouteTypes(
  config: PledgeConfig,
  outputPath?: string,
): Promise<string> {
  const appDir = join(config.rootDir, config.appDir);
  const files = await scanAppDir(appDir);
  const routes = resolveRoutes(files, config);
  const content = generateRouteTypes(routes, config);

  const outPath = outputPath ?? join(config.rootDir, config.outDir, '__pledge_route_types.d.ts');
  await mkdir(join(outPath, '..'), { recursive: true });
  await writeFile(outPath, content, 'utf-8');

  return outPath;
}
