import { createEdgeHandler } from 'pledgestack-server';
import type { PledgeConfig } from 'pledgestack-shared';
import { createEdgeConfig, type EdgeBundleConfig } from './index';

export { createEdgeConfig, type EdgeBundleConfig };

/**
 * Cloudflare Workers adapter for PledgeStack.
 *
 * PledgePack generates an edge-safe bundle. This adapter provides the
 * Cloudflare Workers entry point that wraps PledgeStack's edge handler.
 *
 * Usage in wrangler.toml:
 * ```toml
 * [build]
 * command = "pledgestack build --edge cloudflare"
 * ```
 *
 * Entry point (generated by PledgePack):
 * ```typescript
 * import { createCloudflareHandler } from 'pledgestack-adapters/cloudflare';
 *
 * export default {
 *   async fetch(request: Request, env: Record<string, string>): Promise<Response> {
 *     return createCloudflareHandler({ config })(request, env);
 *   }
 * };
 * ```
 */

export interface CloudflareEnv {
  [key: string]: string;
  ASSETS?: { fetch: (request: Request) => Promise<Response> };
}

export function createCloudflareAdapter(config: PledgeConfig) {
  const handler = createEdgeHandler({ config });

  return {
    /** Cloudflare Workers fetch handler */
    async fetch(request: Request, env?: CloudflareEnv): Promise<Response> {
      // Try static assets first (Cloudflare Pages)
      if (env?.ASSETS) {
        const assetResponse = await env.ASSETS.fetch(request);
        if (assetResponse.status !== 404) return assetResponse;
      }

      // Fall through to PledgeStack edge handler
      return handler(request);
    },

    /** Get the edge bundle config for PledgePack */
    getEdgeConfig(): EdgeBundleConfig {
      return createEdgeConfig('cloudflare');
    },
  };
}
