/**
 * #294 — PSX Audit Logging.
 *
 * Logs all Rust function calls with sanitized arguments, execution time,
 * and caller route for security audit and performance monitoring.
 *
 * The audit logger wraps the `rust` namespace generated by PSX codegen,
 * intercepting every call to record:
 * - Function name
 * - Sanitized arguments (secrets redacted, large values truncated)
 * - Execution time (milliseconds)
 * - Caller route (extracted from AsyncLocalStorage request context)
 * - Success/failure status
 * - Error message on failure
 *
 * Usage:
 *   import { createAuditedRust } from 'pledgestack';
 *   const rust = createAuditedRust(addon, { route: '/api/users' });
 *   const users = await rust.get_users(); // automatically logged
 */

import { AsyncLocalStorage } from 'node:async_hooks';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PsxAuditEntry {
  timestamp: string;
  functionName: string;
  module: string;
  args: unknown[];
  durationMs: number;
  route?: string;
  success: boolean;
  error?: string;
  fallbackUsed?: boolean;
}

export interface PsxAuditConfig {
  /** Log file path (default: '.pledge/psx-audit.log') */
  filePath?: string;
  /** Also log to console (default: false in production, true in dev) */
  console?: boolean;
  /** Max argument value length before truncation (default: 200 chars) */
  maxArgLength?: number;
  /** Keys to redact from arguments (default: password, secret, token, key, auth) */
  redactKeys?: string[];
  /** Sample rate for logging (0-1, default: 1 = log all) */
  sampleRate?: number;
  /** Max file size before rotation in bytes (default: 50MB) */
  maxFileSize?: number;
  /** Whether audit logging is enabled (default: true) */
  enabled?: boolean;
}

export interface AuditContext {
  route?: string;
  module?: string;
}

// ---------------------------------------------------------------------------
// Sensitive key detection
// ---------------------------------------------------------------------------

const DEFAULT_REDACT_KEYS = [
  'password',
  'passwd',
  'secret',
  'token',
  'apikey',
  'api_key',
  'authorization',
  'auth',
  'key',
  'privatekey',
  'private_key',
  'credential',
  'cookie',
  'session',
];

/**
 * Sanitizes an argument value for audit logging.
 * - Redacts sensitive keys
 * - Truncates long values
 * - Serializes objects to JSON
 */
export function sanitizeArg(
  value: unknown,
  config: PsxAuditConfig,
): unknown {
  const maxLen = config.maxArgLength ?? 200;
  const redactKeys = config.redactKeys ?? DEFAULT_REDACT_KEYS;

  if (value === null || value === undefined) return value;

  if (typeof value === 'string') {
    return value.length > maxLen
      ? value.slice(0, maxLen) + '...[truncated]'
      : value;
  }

  if (typeof value === 'number' || typeof value === 'boolean') {
    return value;
  }

  if (Buffer.isBuffer(value)) {
    return `[Buffer:${value.length}bytes]`;
  }

  if (value instanceof Uint8Array) {
    return `[Uint8Array:${value.length}bytes]`;
  }

  if (typeof value === 'object') {
    try {
      const sanitized = sanitizeObject(value, redactKeys, new Set());
      const json = JSON.stringify(sanitized);
      return json.length > maxLen
        ? JSON.stringify(sanitized).slice(0, maxLen) + '...[truncated]'
        : sanitized;
    } catch {
      return '[unserializable]';
    }
  }

  return String(value);
}

function sanitizeObject(
  obj: unknown,
  redactKeys: string[],
  seen: Set<unknown>,
): unknown {
  if (obj === null || typeof obj !== 'object') return obj;
  if (seen.has(obj)) return '[circular]';
  seen.add(obj);

  if (Array.isArray(obj)) {
    return obj.map((item) => sanitizeObject(item, redactKeys, seen));
  }

  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj as Record<string, unknown>)) {
    const lowerKey = key.toLowerCase();
    if (redactKeys.some((rk) => lowerKey.includes(rk))) {
      result[key] = '[REDACTED]';
    } else if (typeof value === 'object' && value !== null) {
      result[key] = sanitizeObject(value, redactKeys, seen);
    } else {
      result[key] = value;
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Audit context via AsyncLocalStorage
// ---------------------------------------------------------------------------

const auditContextStorage = new AsyncLocalStorage<AuditContext>();

/**
 * Sets the audit context (route, module) for the current async scope.
 * This is typically called by the request handler to tag all Rust calls
 * within a request with the route being served.
 */
export function setAuditContext(ctx: AuditContext): void {
  auditContextStorage.enterWith(ctx);
}

/**
 * Gets the current audit context from AsyncLocalStorage.
 */
export function getAuditContext(): AuditContext | undefined {
  return auditContextStorage.getStore();
}

// ---------------------------------------------------------------------------
// PSX Audit Logger
// ---------------------------------------------------------------------------

export class PsxAuditLogger {
  private config: Required<PsxAuditConfig>;
  private initialized = false;
  private fileSize = 0;

  constructor(config: PsxAuditConfig = {}) {
    this.config = {
      filePath: config.filePath ?? '.pledge/psx-audit.log',
      console: config.console ?? process.env.NODE_ENV !== 'production',
      maxArgLength: config.maxArgLength ?? 200,
      redactKeys: config.redactKeys ?? DEFAULT_REDACT_KEYS,
      sampleRate: config.sampleRate ?? 1,
      maxFileSize: config.maxFileSize ?? 50 * 1024 * 1024,
      enabled: config.enabled ?? true,
    };
  }

  /**
   * Logs a PSX audit entry.
   */
  async log(entry: Omit<PsxAuditEntry, 'timestamp'>): Promise<void> {
    if (!this.config.enabled) return;
    if (Math.random() > this.config.sampleRate) return;

    const fullEntry: PsxAuditEntry = {
      timestamp: new Date().toISOString(),
      ...entry,
    };

    const line = JSON.stringify(fullEntry) + '\n';

    if (this.config.console) {
      const status = entry.success ? '✓' : '✗';
      const fallback = entry.fallbackUsed ? ' (fallback)' : '';
      console.log(
        `[psx-audit] ${status} ${entry.module}.${entry.functionName} ${entry.durationMs}ms${fallback}${entry.route ? ` route=${entry.route}` : ''}`,
      );
    }

    await this.writeToFile(line);
  }

  private async writeToFile(line: string): Promise<void> {
    try {
      if (!this.initialized) {
        const { mkdir } = await import('node:fs/promises');
        const { dirname } = await import('node:path');
        await mkdir(dirname(this.config.filePath), { recursive: true });
        this.initialized = true;
      }

      // Check if we need to rotate
      if (this.fileSize + line.length > this.config.maxFileSize) {
        await this.rotateFile();
      }

      const { appendFile } = await import('node:fs/promises');
      await appendFile(this.config.filePath, line);
      this.fileSize += line.length;
    } catch {
      // Ignore file errors — audit logging should not break the app
    }
  }

  private async rotateFile(): Promise<void> {
    try {
      const { rename } = await import('node:fs/promises');
      await rename(this.config.filePath, `${this.config.filePath}.old`);
      this.fileSize = 0;
    } catch {
      // If rename fails, just reset the size counter
      this.fileSize = 0;
    }
  }

  /**
   * Wraps a function with audit logging.
   * Returns a new function that logs the call before and after execution.
   */
  wrap<T extends (...args: never[]) => unknown | Promise<unknown>>(
    fn: T,
    functionName: string,
    module: string,
  ): T {
    const logger = this;

    const wrapped = async function (...args: never[]): Promise<unknown> {
      const ctx = getAuditContext();
      const startTime = performance.now();
      let success = true;
      let error: string | undefined;
      let fallbackUsed = false;

      try {
        const result = await fn(...args);
        return result;
      } catch (err) {
        success = false;
        error = err instanceof Error ? err.message : String(err);
        // Check if this is a fallback scenario
        if (error.includes('not found') || error.includes('Cannot find module')) {
          fallbackUsed = true;
        }
        throw err;
      } finally {
        const durationMs = Math.round(performance.now() - startTime);
        const sanitizedArgs = args.map((arg) => sanitizeArg(arg, logger.config));

        if (logger.config.enabled && Math.random() <= logger.config.sampleRate) {
          await logger.log({
            functionName,
            module,
            args: sanitizedArgs,
            durationMs,
            route: ctx?.route,
            success,
            error,
            fallbackUsed,
          });
        }
      }
    } as T;

    return wrapped;
  }

  /**
   * Wraps all functions on an object (the `rust` namespace) with audit logging.
   * Returns a new object where every function is wrapped.
   */
  wrapModule<T extends Record<string, unknown>>(
    module: T,
    moduleName: string,
  ): T {
    const result: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(module)) {
      if (typeof value === 'function') {
        result[key] = this.wrap(
          value as (...args: never[]) => unknown | Promise<unknown>,
          key,
          moduleName,
        );
      } else {
        result[key] = value;
      }
    }
    return result as T;
  }
}

// ---------------------------------------------------------------------------
// Singleton instance
// ---------------------------------------------------------------------------

let defaultLogger: PsxAuditLogger | null = null;

export function getDefaultPsxAuditLogger(): PsxAuditLogger {
  if (!defaultLogger) {
    defaultLogger = new PsxAuditLogger();
  }
  return defaultLogger;
}

export function setDefaultPsxAuditLogger(logger: PsxAuditLogger): void {
  defaultLogger = logger;
}

// ---------------------------------------------------------------------------
// createAuditedRust — wraps the `rust` namespace from PSX codegen
// ---------------------------------------------------------------------------

/**
 * Creates an audited version of the `rust` namespace.
 * Every function call is logged with sanitized arguments, execution time,
 * and the current route from AsyncLocalStorage.
 *
 * @example
 * ```typescript
 * import { createAuditedRust } from 'pledgestack';
 * import { rust as rawRust } from './__psx_module';
 *
 * const rust = createAuditedRust(rawRust, 'user-service');
 * const users = await rust.get_users(); // automatically logged
 * ```
 */
export function createAuditedRust<T extends Record<string, unknown>>(
  rustNamespace: T,
  moduleName: string,
  config?: PsxAuditConfig,
): T {
  const logger = config
    ? new PsxAuditLogger(config)
    : getDefaultPsxAuditLogger();
  return logger.wrapModule(rustNamespace, moduleName);
}
