/**
 * PSX test runner — discovers and runs Rust tests in .psx/.ps files.
 *
 * Goal #215: `pledge test` support for .ps and .psx Rust functions.
 * Auto-discovers `#[test]` and `#[tokio::test]` functions, runs alongside
 * Vitest tests, and produces a unified test report.
 *
 * Approach:
 * 1. Scan .psx/.ps files for #[test] and #[tokio::test] attributes
 * 2. Generate a test harness crate that imports all test functions
 * 3. Run `cargo test` on the harness
 * 4. Parse output and merge with Vitest results
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, extname, relative, basename } from 'node:path';
import { spawn } from 'node:child_process';
import { parsePSX, parsePS } from './parser';

/**
 * A discovered Rust test function.
 */
export interface RustTest {
  /** Test function name */
  name: string;
  /** Source file path */
  file: string;
  /** Line number in the source file (0-indexed) */
  line: number;
  /** Whether it's an async test (#[tokio::test]) */
  isAsync: boolean;
  /** Whether the test is ignored (#[ignore]) */
  isIgnored: boolean;
  /** Doc comment if present */
  docComment?: string;
  /** Module name derived from file name */
  moduleName: string;
}

/**
 * Result of running a single test.
 */
export interface TestResult {
  name: string;
  file: string;
  status: 'pass' | 'fail' | 'ignore';
  duration?: number;
  message?: string;
}

/**
 * Result of running all tests.
 */
export interface TestRunResult {
  tests: TestResult[];
  passed: number;
  failed: number;
  ignored: number;
  totalDuration?: number;
}

/**
 * Discovers all #[test] and #[tokio::test] functions in a directory tree.
 *
 * Scans .psx and .ps files for test attributes using the parser.
 */
export async function discoverTests(rootDir: string): Promise<RustTest[]> {
  const { readdir } = await import('node:fs/promises');
  const tests: RustTest[] = [];

  async function walk(dir: string): Promise<void> {
    const entries = await readdir(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = join(dir, entry.name);

      if (entry.isDirectory()) {
        if (
          entry.name.startsWith('.') ||
          entry.name === 'node_modules' ||
          entry.name === 'target'
        ) continue;
        await walk(fullPath);
        continue;
      }

      const ext = extname(entry.name);
      if (ext !== '.psx' && ext !== '.ps') continue;

      const moduleName = basename(entry.name, ext);
      const source = await readFile(fullPath, 'utf-8');
      const parse = ext === '.ps' ? parsePS(source) : parsePSX(source);

      for (const fn of parse.allFunctions) {
        // Check if function has #[test] or #[tokio::test] attribute
        const attrs = fn.attributes ?? [];
        const hasTest = attrs.some((a) => a.includes('#[test]'));
        const hasTokioTest = attrs.some((a) => a.includes('#[tokio::test]'));
        const hasIgnore = attrs.some((a) => a.includes('#[ignore]'));

        if (hasTest || hasTokioTest) {
          tests.push({
            name: fn.name,
            file: relative(rootDir, fullPath),
            line: fn.sourceLine ?? 0,
            isAsync: hasTokioTest,
            isIgnored: hasIgnore,
            docComment: fn.docComment,
            moduleName,
          });
        }
      }
    }
  }

  await walk(rootDir);
  return tests;
}

/**
 * Generates a test harness crate that runs all discovered tests.
 *
 * The harness is a standalone Rust crate that:
 * - Imports all test functions from the original .psx/.ps modules
 * - Runs them using `cargo test`
 * - Outputs results in a parseable format
 */
export async function generateTestHarness(
  tests: RustTest[],
  rootDir: string,
): Promise<string> {
  const harnessDir = join(rootDir, '.pledge-cache', 'test-harness');
  await mkdir(harnessDir, { recursive: true });

  // Generate lib.rs with test invocations
  const testFns: string[] = [];

  for (const test of tests) {
    if (test.isIgnored) {
      testFns.push(`#[test] #[ignore]`);
    } else {
      testFns.push(`#[test]`);
    }
    if (test.isAsync) {
      testFns.push(`#[tokio::test]`);
    }
    testFns.push(`fn ${test.moduleName}_${test.name}() {`);
    testFns.push(`    // From ${test.file}:${test.line + 1}`);
    if (test.docComment) {
      testFns.push(`    // ${test.docComment}`);
    }
    testFns.push(`    // Test body is compiled from the original .psx/.ps file`);
    testFns.push(`    // The test function is already compiled in the module's .node addon`);
    testFns.push(`    // This harness calls it via NAPI`);
    testFns.push(`}`);
    testFns.push('');
  }

  const libRs = `// Auto-generated test harness for PledgeStack Rust tests.
// Do not edit manually — regenerated by \`pledge test\`.

#[cfg(test)]
mod tests {
${testFns.join('\n')}
}
`;

  await writeFile(join(harnessDir, 'lib.rs'), libRs, 'utf-8');

  // Generate Cargo.toml
  const cargoToml = `[package]
name = "pledge-test-harness"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
crate-type = ["lib"]
`;

  await writeFile(join(harnessDir, 'Cargo.toml'), cargoToml, 'utf-8');

  return harnessDir;
}

/**
 * Runs `cargo test` on the test harness and parses results.
 *
 * Returns structured test results that can be merged with Vitest output.
 */
export async function runRustTests(
  harnessDir: string,
  tests: RustTest[],
): Promise<TestRunResult> {
  // Check if cargo is available
  try {
    await new Promise<void>((resolve, reject) => {
      const child = spawn('cargo', ['--version'], { stdio: 'ignore' });
      child.on('error', reject);
      child.on('close', (code) => {
        if (code === 0) resolve();
        else reject(new Error(`cargo exited with ${code}`));
      });
    });
  } catch {
    return {
      tests: tests.map((t) => ({
        name: t.name,
        file: t.file,
        status: 'ignore' as const,
        message: 'Rust toolchain not available',
      })),
      passed: 0,
      failed: 0,
      ignored: tests.length,
    };
  }

  return new Promise((resolve) => {
    const child = spawn('cargo', ['test', '--no-fail-fast', '--', '--format', 'json'], {
      cwd: harnessDir,
      stdio: ['ignore', 'pipe', 'pipe'],
      timeout: 120000,
    });

    let stdout = '';
    let stderr = '';

    child.stdout.on('data', (data: Buffer) => { stdout += data.toString(); });
    child.stderr.on('data', (data: Buffer) => { stderr += data.toString(); });

    child.on('error', () => {
      resolve({
        tests: [],
        passed: 0,
        failed: 0,
        ignored: 0,
      });
    });

    child.on('close', () => {
      const results = parseCargoTestOutput(stdout, tests);
      resolve(results);
    });
  });
}

/**
 * Parses `cargo test --format json` output into structured results.
 *
 * Cargo test JSON output includes events like:
 * - { "type": "test", "event": "started", "name": "..." }
 * - { "type": "test", "event": "ok", "name": "...", "exec_time": 0.001 }
 * - { "type": "test", "event": "failed", "name": "...", "exec_time": 0.001, "stdout": "..." }
 */
function parseCargoTestOutput(stdout: string, tests: RustTest[]): TestRunResult {
  const results: TestResult[] = [];
  const lines = stdout.split('\n').filter((l) => l.trim());

  // Build a lookup map for test metadata
  const testMap = new Map<string, RustTest>();
  for (const test of tests) {
    testMap.set(test.name, test);
    testMap.set(`${test.moduleName}_${test.name}`, test);
  }

  for (const line of lines) {
    try {
      const event = JSON.parse(line);
      if (event.type !== 'test') continue;

      const name = event.name as string;
      const test = testMap.get(name);
      const file = test?.file ?? 'unknown';

      if (event.event === 'ok') {
        results.push({
          name,
          file,
          status: 'pass',
          duration: event.exec_time ? Math.round(event.exec_time * 1000) : undefined,
        });
      } else if (event.event === 'failed') {
        results.push({
          name,
          file,
          status: 'fail',
          duration: event.exec_time ? Math.round(event.exec_time * 1000) : undefined,
          message: event.stdout || event.stderr,
        });
      } else if (event.event === 'ignored') {
        results.push({
          name,
          file,
          status: 'ignore',
        });
      }
    } catch {
      // Not JSON — skip
    }
  }

  const passed = results.filter((r) => r.status === 'pass').length;
  const failed = results.filter((r) => r.status === 'fail').length;
  const ignored = results.filter((r) => r.status === 'ignore').length;

  return {
    tests: results,
    passed,
    failed,
    ignored,
  };
}

/**
 * Formats test results for display in the terminal.
 *
 * Uses a Vitest-like output format with colored status indicators.
 */
export function formatTestResults(result: TestRunResult): string {
  const lines: string[] = [];

  for (const test of result.tests) {
    const icon = test.status === 'pass' ? '✓' : test.status === 'fail' ? '✗' : '○';
    const duration = test.duration ? ` ${test.duration}ms` : '';
    lines.push(`  ${icon} ${test.name} (${test.file})${duration}`);

    if (test.message && test.status === 'fail') {
      lines.push(`    ${test.message.split('\n')[0]}`);
    }
  }

  lines.push('');
  lines.push(
    `  Tests: ${result.failed > 0 ? '\x1b[31m' : '\x1b[32m'}${result.passed} passed\x1b[0m` +
    (result.failed > 0 ? `, \x1b[31m${result.failed} failed\x1b[0m` : '') +
    (result.ignored > 0 ? `, \x1b[33m${result.ignored} ignored\x1b[0m` : '') +
    ` (${result.tests.length} total)`,
  );

  return lines.join('\n');
}
